### PR TITLE
Issue #29 : Jira style

### PR DESCRIPTION
**Pull request by pikulsky**
Added Jira style table

### CODE REVIEW

**Comment by ozh** [comment]
This PR is merged but incomplete: Jira doesn't appear in the style drop down list.

**Comment by pikulsky** [comment]
I do see "jira" in drop down list, under Github Markdown, see the attached screenshot. 
image

**Comment by ozh** [comment]
Indeed, shows on Chrome and even IE but not on Firefox...

**Comment by ozh** [comment]
Hmmm it shows now. Probably a cache problem, yet I refreshed several times... All things OK, you can move along :)

**Pull request merged**
