### PR TITLE
Added feature for saving, loading, and resetting table text.

### PR DESCRIPTION
**Pull request by ghost**
Hiya, please see PR for a new feature that allows persistant storage of the table text, even through reload. Using cookies, this saves on textbox input, and saves you from all the annoying internet crashes and accidental reoads that mean you've lost all your data. Also offers a feature for resetting to the default table.

### CODE REVIEW

**Comment by ozh** [comment]
What's the deal with 'retVal121' ?

**Comment by ghost** [comment]
@ozh Hiya, it's the string match for a newline, it's a messy solution I know, but I wasn't sure how else to do it. You can change it or make it a bit more robust. I tried using \r\n but it didn't work

**Comment by ozh** [comment]
I don't get why you replace newlines back and forth (but maybe I don't get something obvious)

Also, it's beyond messy: why add JS in the HTML file when there's a JS file ??

**Comment by ghost** [comment]
@ozh you raise a good point with the JS file, my HTML isn't the cleanest :). I used the newline replacement because if you try creating the cookie with the returns there, it only adds the first line, then if you use `\r\n` it decides to keep it because it's recognized as a line break and as such can't replace it (without the replace the return character just shows in the text. It's not a bug, it's an easter egg :-)

**Comment by ozh** [comment]
I think encoding/decoding (encodeURI) would be much simpler...
I'm all for this feature, but clean code please

**Pull request closed without merging**
