### PR TITLE
Created auto save and load feature with a reset to default button

### PR DESCRIPTION
**Pull request by ghost**
Hi, I came across this nice little app and decided to improve it a bit. Please feedback with any comments etc., thanks. As the title says, I added a simple feature to load a cookie and as such the user has a saved version of their table when they come back to it. Helpful for crashing internet, closing browser, etc. I also added another commit to fix the chinese characters issue

### CODE REVIEW

**Comment by alexisLefebvre** [comment]
It looks like your PR address several bugs, PRs usually contain only one change. Your commit on Chinese characters should probably be moved to another PR.

**Comment by ghost** [comment]
@alexislefebvre Hi Alexis, I'll roll back the chinese characters change but I'm not sure how to open two seperate pull requests for the same repo, could you expand? Thanks

**Comment by alexisLefebvre** [comment]
@rhys0178 You have to create as many branches as PR. https://help.github.com/articles/using-pull-requests/

**Comment by alexisLefebvre** [comment]
@rhys0178 So you have to create another branch for the fix about Chinese characters.

<del>About this PR, you can also remove the last commit then force push: http://stackoverflow.com/questions/4647301/rolling-back-local-and-remote-git-repository-by-1-commit/4647362#4647362 You'll be able to reopen this PR and it should contain only 2 commits.</del> Edit: I just saw that this PR contain some commits from another user, that's probably not what you wanted to do.

**Comment by ghost** [comment]
Hi @alexislefebvre, please see these links for the new PR's:
https://github.com/ozh/ascii-tables/pull/10
https://github.com/ozh/ascii-tables/pull/9

Apologies, the 'other user' is actually my other account, but I messed up the user details -.-

**Pull request closed without merging**
